//! Generated FFI bindings to the NVIDIA NPP image-processing domain.
//!
//! Auto-generated by `bindgen` from `wrapper.h`. Scoped to `nppi*` symbols only
//! (NPP image domain; `npps*` signal symbols are excluded).
//! The bindings are generated into `OUT_DIR` and are never committed.
//!
//! # Safety
//!
//! These are raw `extern "C"` bindings. Use the `npp-rs` crate for safe wrappers.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
